"""
Policy Exporter for Nadir Bipedal Walker:
Exports Stable-Baselines3 PyTorch Policy to:
1. ONNX (.onnx) for ONNX Runtime / Edge TPU
2. MicroPython weights (.py) for ESP32
3. C Header (.h) for bare-metal Arduino / STM32
"""

import argparse
import os
import sys
import torch
import numpy as np

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from stable_baselines3 import PPO


class OnnxPolicyWrapper(torch.nn.Module):
    """
    Lightweight forward wrapper for PPO deterministic actor policy.
    """
    def __init__(self, policy):
        super().__init__()
        self.mlp_extractor = policy.mlp_extractor.policy_net
        self.action_net = policy.action_net

    def forward(self, obs: torch.Tensor) -> torch.Tensor:
        latent = self.mlp_extractor(obs)
        action = self.action_net(latent)
        # Clip action to [-1.0, 1.0]
        return torch.clamp(action, -1.0, 1.0)


def export_onnx(policy, dummy_input: torch.Tensor, output_path: str):
    try:
        wrapper = OnnxPolicyWrapper(policy)
        wrapper.eval()
        
        torch.onnx.export(
            wrapper,
            dummy_input,
            output_path,
            export_params=True,
            opset_version=14,
            do_constant_folding=True,
            input_names=["observation"],
            output_names=["action"],
            dynamic_axes={"observation": {0: "batch_size"}, "action": {0: "batch_size"}},
        )
        print(f"[Nadir Exporter] Successfully exported ONNX model to: {output_path}")
    except Exception as e:
        print(f"[Nadir Exporter] ONNX export skipped ({e}). Install onnx & onnxscript to enable.")


def export_micropython(policy, output_path: str):
    """
    Extract weights and biases for pure MicroPython matrix multiplication.
    """
    layers = []
    # MLP Policy Net
    for layer in policy.mlp_extractor.policy_net:
        if isinstance(layer, torch.nn.Linear):
            layers.append({
                "weight": layer.weight.detach().cpu().numpy().tolist(),
                "bias": layer.bias.detach().cpu().numpy().tolist(),
            })
    # Action Head
    action_layer = policy.action_net
    layers.append({
        "weight": action_layer.weight.detach().cpu().numpy().tolist(),
        "bias": action_layer.bias.detach().cpu().numpy().tolist(),
    })

    with open(output_path, "w") as f:
        f.write("# Nadir Trained Policy Weights for MicroPython / ESP32\n")
        f.write("# Auto-generated by inference/export_policy.py\n\n")
        f.write(f"LAYERS = {repr(layers)}\n\n")
        f.write("""
def relu(x):
    return [max(0.0, v) for v in x]

def matmul_vec(w, x, b):
    # w: [out_dim, in_dim], x: [in_dim], b: [out_dim]
    out = []
    for row, bias in zip(w, b):
        val = sum(r * xi for r, xi in zip(row, x)) + bias
        out.append(val)
    return out

def predict_action(obs):
    x = obs
    for i, layer in enumerate(LAYERS):
        x = matmul_vec(layer['weight'], x, layer['bias'])
        if i < len(LAYERS) - 1:
            x = relu(x)
        else:
            x = [max(-1.0, min(1.0, v)) for v in x]
    return x
""")
    print(f"[Nadir Exporter] Successfully exported MicroPython policy to: {output_path}")


def main():
    parser = argparse.ArgumentParser(description="Export Nadir PPO Policy")
    parser.add_argument("--model", type=str, default="checkpoints/pretrained_ppo_walker.zip", help="Input model path")
    parser.add_argument("--output-dir", type=str, default="exported_models", help="Output directory")
    args = parser.parse_args()

    os.makedirs(args.output_dir, exist_ok=True)

    # Search for fallback model if default not present
    if not os.path.exists(args.model):
        candidates = [
            "../walker/ppo_bipedal_walker.zip",
            "checkpoints/pretrained_ppo_walker.zip",
            "checkpoints/nadir_ppo_final.zip",
        ]
        for c in candidates:
            if os.path.exists(c):
                args.model = c
                break

    print(f"[Nadir Exporter] Loading model: {args.model}")
    model = PPO.load(args.model)
    policy = model.policy

    dummy_input = torch.randn(1, 17, dtype=torch.float32)

    onnx_path = os.path.join(args.output_dir, "nadir_policy.onnx")
    mpy_path = os.path.join(args.output_dir, "nadir_weights.py")

    export_onnx(policy, dummy_input, onnx_path)
    export_micropython(policy, mpy_path)
    print("\n[Nadir Exporter] All exports completed successfully!")


if __name__ == "__main__":
    main()
